version: "3.2"

services:
  tests:
    build:
      context: .
    image: website-tests
    container_name: 'website-tests'
    command: ["python3", "main.py"]
    volumes:
        - ${PWD}/latest_runs.json:/latest_runs.json
        - ${PWD}/out.tsv:/out.tsv
        - ${PWD}/run.log:/run.log